import streamlit as st
import pandas as pd
from agents.recommendation_agent import get_recommendation
from agents.prediction_agent import predict_flare
from agents.alert_agent import generate_alert
from agents.security_agent import validate_input
from agents.gemini_agent import explain_risk
st.title("☀️ SolarGuard AI")
st.caption("Aditya-L1 Inspired Multi-Agent Solar Flare Forecasting System")
st.subheader("Solar Flare Risk Analyzer")

graph_data = pd.DataFrame({
    "Hour": [1, 2, 3, 4, 5, 6, 7, 8],
    "Xray": [5, 12, 18, 30, 45, 60, 75, 97]
})

st.subheader("📈 Solar Activity Trend")

chart_data = graph_data.set_index("Hour")

st.line_chart(chart_data)

xray_value = st.number_input(
    "Enter X-Ray Intensity",
    min_value=0.0,
    value=25.0
)

if st.button("Analyze"):
    if validate_input(xray_value):

        risk = predict_flare(xray_value)

    # Dynamic confidence
    if risk == "LOW":
        confidence = "88%"
        solar_status = "🟢 Space Weather Stable"

    elif risk == "MEDIUM":
        confidence = "92%"
        solar_status = "🟡Increased Solar Activity Detected"

    else:
        confidence = "97%"
        solar_status = "🔴Severe Solar Activity Warning"

    recommendation = get_recommendation(risk)

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Current Risk", risk)

    with col2:
        st.metric("Confidence", confidence)

    with col3:
        st.markdown("### Solar Status")
        st.info(solar_status)

    # Risk Indicator
    if risk == "LOW":
        st.success("Risk Level: LOW")

    elif risk == "MEDIUM":
        st.warning("Risk Level: MEDIUM")

    else:
        st.error("Risk Level: HIGH")

    alert = generate_alert(risk)
    explanation = explain_risk(risk)

    st.success(alert)

    st.subheader("AI Impact Analysis")
    st.write(explanation)

    st.subheader("Recommended Actions")
    st.info(recommendation)

    # Downloadable Report
    report = f"""
```

# SolarGuard AI Early Warning Report

Risk Level: {risk}

Confidence: {confidence}

Solar Status: {solar_status}

Impact Analysis:
{explanation}

Recommended Actions:
{recommendation}

Generated by SolarGuard AI
Aditya-L1 Inspired Multi-Agent Solar Flare Forecasting System
"""

    st.download_button(
        label="📄 Download Early Warning Report",
        data=report,
        file_name="SolarGuard_Report.txt",
        mime="text/plain"
    )

    st.markdown("---")

    st.subheader("AI Agent Architecture")

    st.markdown("""
```

1. Security Agent validates input
2. Prediction Agent estimates flare risk
3. Alert Agent generates warnings
4. Gemini Agent explains consequences
5. Recommendation Agent suggests actions
6. Report Agent generates downloadable reports
   """)

    st.subheader("Why This Matters")

    st.markdown("""
   ```

Solar flares can affect:

* Satellite communications
* GPS navigation systems
* Aviation and maritime operations
* Electrical power grids

SolarGuard AI provides an intelligent early-warning mechanism
for monitoring potential space weather risks.
""")

st.info("""
```

SolarGuard AI is a multi-agent system inspired by Aditya-L1 mission data.
It analyzes solar X-ray intensity and predicts potential impacts on GPS,
satellites, and communication systems.
""")
st.subheader("Future Scope")

st.markdown("""
- Integration with Aditya-L1 SoLEXS data
- Integration with HEL1OS hard X-ray observations
- Real-time space weather monitoring
- Automated alert notifications
- Satellite risk assessment dashboard
""")
